# Stage 1: Build the application
FROM node:18-alpine as builder

# Set working directory
WORKDIR /app

# Install dependencies
COPY package.json ./
RUN npm install -cf  

# Copy application code
COPY . .

# Build the application
RUN npm run build

# Stage 2: Run the application
FROM node:18-alpine

# Set working directory
WORKDIR /app

# Copy built application from builder
COPY --from=builder /app ./

# Expose port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "dev"]